---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
temp <- as.matrix(read.csv("/Users/ltrujillo/Desktop/REFERENCE-v3.csv", header = F)) 
```

```{r}
directory <-"/Users/ltrujillo/Desktop/Cor_Rest_of_points_dim12/"

load_persistence_variable <- function(directory, n){
  return(as.matrix(read.csv(file = paste0(directory, "rest_of_points", temp[n], ".csv")), header = T)[,-1])
}

pers_index_start <- 1
pers_index_end <- 2000
#For loop will generate persistence variables.

for(i in seq(from = pers_index_start, to = pers_index_end)){
  print(i)
  assign(paste0("persistence", i), load_persistence_variable(directory, i))
}
```
#Counting dimensions
```{r} 
Counting_Dimensions <- function(n){
  tempFrame <- data.frame("Dimension" = get(paste0("persistence", n))[,1], "Birth" = get(paste0("persistence", n))[,2], "Death" = get(paste0("persistence", n))[,3])  
  return(table(tempFrame$Dimension))
}
```

#Extract noise.
```{r} 
good_pers_index <- c()
pers_bad_index0 <- c()
pers_bad_index1 <- c()
pers_bad_index2 <- c()
pers_bad_index12 <- c()

for(i in seq(from = pers_index_start, to = pers_index_end)){
  if(!is.na(Counting_Dimensions(i)[1]) & !is.na(Counting_Dimensions(i)[2])){
    good_pers_index <- append(good_pers_index, i)
  }
}
for(i in seq(from = pers_index_start, to = pers_index_end)){
  if(is.na(Counting_Dimensions(i)[1])){ #Check for files with no 1 dimensional features
    pers_bad_index1 <- append(pers_bad_index1, i)
  }
  if(is.na(Counting_Dimensions(i)[2]) ){ #Check for files with no 2 dimensional features
    pers_bad_index2 <- append(pers_bad_index2, i)
  }
}

bad_files_dim1 <- c()
bad_files_dim2 <- c()
bad_files_dim12 <- c()

bad_normal <- c()
bad_af <- c()
bad_r <- c()
bad_o <- c()


for(i in pers_bad_index2){
  if(temp[i,2] == "N"){
    bad_normal <- append(bad_normal, i)
  }
  if(temp[i,2] == "A"){
    bad_af <- append(bad_af, i )
  }
  if(temp[i,2] == "~"){
    bad_r <- append(bad_r, i)
  }
  if(temp[i,2] == "O"){
    bad_o <- append(bad_o, i)
  }
}


for(i in pers_bad_index1){
  bad_files_dim1 <- append(bad_files_dim1, temp[i,2])
}

for(i in pers_bad_index2){
  bad_files_dim2 <- append(bad_files_dim2, temp[i, 2])
  
}

for(i in pers_bad_index12){
  bad_files_dim12 <- append(bad_files_dim12, temp[i,2])
}
```

##Distance to diagonal. The points we compute this are non-persistent points; persistence diagrams for which the persistent points are removed. 
```{r}
dist_diagonal_dim_1 <- function(pers, n){
  d_distance <- c()
  for(i in seq(Counting_Dimensions(n)[1])){ 
    x <- pers[i,2]
    y <- pers[i,3]
    d_distance <- append(d_distance, abs(y-x)/sqrt(2))
  }
  return(d_distance)
}
 
dist_diagonal_dim_2 <- function(pers,n){
  d_distance <- c()
  if(i %in% good_pers_index){
    for(i in seq(from = Counting_Dimensions(n)[1]+1, to = Counting_Dimensions(n)[1] + Counting_Dimensions(n)[2])){
      x <- pers[i,2]
      y <- pers[i,3]
      d_distance <- append(d_distance, abs(y-x)/sqrt(2))
    }
  }
  else{
    d_distance <- append(d_distance, 0)
  }
  return(d_distance)
}
```

#Compute the average diagonal distances.
```{r}
avg_dist_dim_1 <- c() 
avg_dist_dim_2 <- c()

sd_dist_dim_1 <- c()
sd_dist_dim_2 <- c()

#Stpre one dimension mean of diag dist.
for(i in seq(from = pers_index_start, to = pers_index_end)){
  avg_dist_dim_1 <- append(avg_dist_dim_1, mean(dist_diagonal_dim_1(get(paste0("persistence", i)), i)))
}

#Store two dimension mean of diag dist
for(i in seq(from = pers_index_start, to = pers_index_end)){
  if(!is.na(Counting_Dimensions(i)[2])){
    avg_dist_dim_2 <- append(avg_dist_dim_2, mean(dist_diagonal_dim_2(get(paste0("persistence", i)), i)))
  }
  else{
    avg_dist_dim_2 <- append(avg_dist_dim_2, 400)
  }
}
  
#Store one dimension sd of diag dist.
for(i in seq(from = pers_index_start, to = pers_index_end)){
  hold_pers <- get(paste0("persistence", i))
  if(Counting_Dimensions(i)[1] > 1){
    sd_dist_dim_1 <- append(sd_dist_dim_1, sd(dist_diagonal_dim_1(hold_pers, i)))
  }
  else{
    sd_dist_dim_1 <- append(sd_dist_dim_1, 900)
  }
}

#Store two dimension sd of diag dist.
for(i in seq(from = pers_index_start, to = pers_index_end)){
  hold_pers <- get(paste0("persistence", i))
  if(is.na(Counting_Dimensions(i)[2])){#If there are second dimensional features
    
    if(Counting_Dimensions(i)[2] > 1){#If there is more than one second dimensional feature
      sd_dist_dim_2 <- append(sd_dist_dim_2, sd(dist_diagonal_dim_1(hold_pers, i)))
    }
    else{ #If not, give bad statistic
      sd_dist_dim_2 <- append(sd_dist_dim_2, 1000)
    }
  }
  else{ #If there are no second dimensional features, give bad statistic. 
    sd_dist_dim_2 <- append(sd_dist_dim_2, 500)
  }
}

```

#Store the diagonal distances in a CSV
```{r}
distances <- data.frame("avg_dist_dim1" = avg_dist_dim_1, "avg_dist_dim2" = avg_dist_dim_2, "sd_dist_dim1" = sd_dist_dim_1, "sd_dist_dim2" = sd_dist_dim_2)
write.csv(distances, file = "0_2000_diag_dist_mean_sd.csv")
```
